# frozen_string_literal: true

source "https://rubygems.org"

# git_source(:github) {|ernest-phillips.github.io| "https://github.com/ernest-phillips.github.io" }

# gem "rails"
gem "jekyll"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end